/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    villages: Village;
    'family-members': FamilyMember;
    'family-relationships': FamilyRelationship;
    events: Event;
    news: News;
    'gallery-items': GalleryItem;
    'committee-members': CommitteeMember;
    documents: Document;
    'contact-submissions': ContactSubmission;
    'audit-log': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    villages: VillagesSelect<false> | VillagesSelect<true>;
    'family-members': FamilyMembersSelect<false> | FamilyMembersSelect<true>;
    'family-relationships': FamilyRelationshipsSelect<false> | FamilyRelationshipsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'gallery-items': GalleryItemsSelect<false> | GalleryItemsSelect<true>;
    'committee-members': CommitteeMembersSelect<false> | CommitteeMembersSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'hi' | 'gu') | ('en' | 'hi' | 'gu')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'hi' | 'gu';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * One reusable template drives every village page — add all 9 Sayla State villages here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "villages".
 */
export interface Village {
  id: number;
  name: string;
  /**
   * Used in the URL. Leave blank to auto-generate from name.
   */
  slug: string;
  /**
   * Controls display order on the village listing page.
   */
  order?: number | null;
  /**
   * Show this village in the Home page "Featured Village" section.
   */
  featured?: boolean | null;
  coverImage: number | Media;
  /**
   * Short summary shown on the village listing card.
   */
  shortDescription: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  history?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  location?: {
    address?: string | null;
    /**
     * Google Maps embed URL (optional, can be added later).
     */
    mapEmbedUrl?: string | null;
  };
  importantPlaces?:
    | {
        name: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Population / basic information, where available.
   */
  populationInfo?: string | null;
  contactInfo?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * People in a village family tree. Approve (publish) and mark "Public" before they appear on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "family-members".
 */
export interface FamilyMember {
  id: number;
  fullName: string;
  /**
   * Which village family tree this person belongs to.
   */
  village: number | Village;
  /**
   * A person only appears on the public tree once they are both published AND marked Public.
   */
  displayStatus: 'private' | 'public';
  /**
   * Generation number, starting at 1 for the founder/earliest ancestor.
   */
  generation: number;
  profilePhoto?: (number | null) | Media;
  gender?: ('male' | 'female' | 'other') | null;
  /**
   * Optional.
   */
  birthYear?: number | null;
  /**
   * Optional. Leave blank if living.
   */
  deathYear?: number | null;
  shortBiography?: string | null;
  /**
   * Internal notes for the Super Admin only — never shown publicly.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Connects Family Members with parent-child or spouse relationships.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "family-relationships".
 */
export interface FamilyRelationship {
  id: number;
  relationshipType: 'parent-child' | 'spouse';
  parent?: (number | null) | FamilyMember;
  child?: (number | null) | FamilyMember;
  spouseA?: (number | null) | FamilyMember;
  spouseB?: (number | null) | FamilyMember;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Used in the URL. Leave blank to auto-generate from title.
   */
  slug: string;
  /**
   * Leave blank for a community-wide event.
   */
  village?: (number | null) | Village;
  date: string;
  location?: string | null;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  registration?: {
    contactName?: string | null;
    contactPhone?: string | null;
    contactEmail?: string | null;
    registrationUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * Used in the URL. Leave blank to auto-generate from title.
   */
  slug: string;
  type: 'community' | 'village' | 'notice';
  /**
   * Required for village-specific announcements.
   */
  village?: (number | null) | Village;
  date: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  /**
   * Optional document attachment (PDF, etc).
   */
  attachment?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items".
 */
export interface GalleryItem {
  id: number;
  type: 'image' | 'video';
  image?: (number | null) | Media;
  /**
   * YouTube/Vimeo link.
   */
  videoUrl?: string | null;
  caption?: string | null;
  category: 'events' | 'villages' | 'community' | 'heritage';
  /**
   * Optional — for village-wise filtering.
   */
  village?: (number | null) | Village;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committee-members".
 */
export interface CommitteeMember {
  id: number;
  name: string;
  position: string;
  photo?: (number | null) | Media;
  shortDescription?: string | null;
  contactInfo?: {
    phone?: string | null;
    email?: string | null;
  };
  /**
   * Controls display order.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  category: 'forms' | 'notices' | 'rules' | 'reports' | 'other';
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Messages submitted through the public Contact Us form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  subject: string;
  message: string;
  status?: ('new' | 'read' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Read-only record of administrative and genealogy changes. Written automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  collectionSlug: string;
  documentId: string;
  operation: 'create' | 'update' | 'delete';
  performedByEmail?: string | null;
  summary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'villages';
        value: number | Village;
      } | null)
    | ({
        relationTo: 'family-members';
        value: number | FamilyMember;
      } | null)
    | ({
        relationTo: 'family-relationships';
        value: number | FamilyRelationship;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'gallery-items';
        value: number | GalleryItem;
      } | null)
    | ({
        relationTo: 'committee-members';
        value: number | CommitteeMember;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "villages_select".
 */
export interface VillagesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  order?: T;
  featured?: T;
  coverImage?: T;
  shortDescription?: T;
  description?: T;
  history?: T;
  location?:
    | T
    | {
        address?: T;
        mapEmbedUrl?: T;
      };
  importantPlaces?:
    | T
    | {
        name?: T;
        description?: T;
        id?: T;
      };
  populationInfo?: T;
  contactInfo?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "family-members_select".
 */
export interface FamilyMembersSelect<T extends boolean = true> {
  fullName?: T;
  village?: T;
  displayStatus?: T;
  generation?: T;
  profilePhoto?: T;
  gender?: T;
  birthYear?: T;
  deathYear?: T;
  shortBiography?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "family-relationships_select".
 */
export interface FamilyRelationshipsSelect<T extends boolean = true> {
  relationshipType?: T;
  parent?: T;
  child?: T;
  spouseA?: T;
  spouseB?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  village?: T;
  date?: T;
  location?: T;
  description?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  registration?:
    | T
    | {
        contactName?: T;
        contactPhone?: T;
        contactEmail?: T;
        registrationUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  village?: T;
  date?: T;
  description?: T;
  image?: T;
  attachment?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items_select".
 */
export interface GalleryItemsSelect<T extends boolean = true> {
  type?: T;
  image?: T;
  videoUrl?: T;
  caption?: T;
  category?: T;
  village?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committee-members_select".
 */
export interface CommitteeMembersSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  photo?: T;
  shortDescription?: T;
  contactInfo?:
    | T
    | {
        phone?: T;
        email?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  collectionSlug?: T;
  documentId?: T;
  operation?: T;
  performedByEmail?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  home?: {
    heroHeading?: string | null;
    heroSubheading?: string | null;
    /**
     * Full-bleed hero background for desktop/tablet. One image is shown static; two or more auto-rotate as a slideshow. Ignored if a Hero Video is set.
     */
    heroImages?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional — a separate hero background for phone screens. A single wide desktop photo usually crops badly on a narrow screen, so upload a portrait/square-friendly version of the same scene here. Leave empty to reuse the desktop Hero Images above on mobile too. Ignored if a Hero Video is set.
     */
    heroImagesMobile?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional — an uploaded video file (mp4) plays full-bleed behind the hero, muted and looping. Takes priority over Hero Images if set.
     */
    heroVideo?: (number | null) | Media;
    introText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Shown on the Home page above "Our Villages". Leave Content blank to hide the section.
     */
    history?: {
      heading?: string | null;
      content?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      image?: (number | null) | Media;
    };
  };
  about?: {
    introduction?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    historyAndBackground?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    visionAndMission?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    objectives?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    heritageAndCulture?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    achievements?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  contact?: {
    address?: string | null;
    phone?: string | null;
    email?: string | null;
    mapEmbedUrl?: string | null;
  };
  social?:
    | {
        platform?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  home?:
    | T
    | {
        heroHeading?: T;
        heroSubheading?: T;
        heroImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
        heroImagesMobile?:
          | T
          | {
              image?: T;
              id?: T;
            };
        heroVideo?: T;
        introText?: T;
        history?:
          | T
          | {
              heading?: T;
              content?: T;
              image?: T;
            };
      };
  about?:
    | T
    | {
        introduction?: T;
        historyAndBackground?: T;
        visionAndMission?: T;
        objectives?: T;
        heritageAndCulture?: T;
        achievements?: T;
      };
  contact?:
    | T
    | {
        address?: T;
        phone?: T;
        email?: T;
        mapEmbedUrl?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}